### ISSUE TITLE
Instructions in a different language

### ISSUE THREAD

**Issue by gijsschumacher** [iatgen/iatgen#19]
Would it be possible to code a translation of the instructions? The website advices to copy/paste translations, but this is quite tedious and also likely to create errors.

**Comment by Joao-O-Santos** [comment]
Hi, @gijsschumacher !

I think you might be looking for this: https://github.com/iatgen/tr.iatgen
For a more complete tutorial you may wish to take a look at the pdf available here: https://www.protocols.io/view/generating-non-english-iats-and-collecting-offline-kxygx34jdg8j/v1

Feel free to ask any questions.
