### ISSUE TITLE
Cannot Download Legacy Export in Qualtrics

### ISSUE THREAD

**Issue by joneszm** [iatgen/iatgen#22]
I am trying to begin data analyzation, and Qualtrics no longer has the option to download as a Legacy Export CSV so none of the data analysis in Shiny. How do I download the Qualtrics file to make this work?

**Comment by michalkouril** [comment]
Hello,
The standard CSV export from Qualtrics should be able to import into iatgen.org. Please let us know if you are having trouble.
Thanks,
Michal

**Comment by bpulling** [comment]
I just checked my survey and had no problem exporting from qualtrics
